In [1]:
import sys
sys.path.insert(1, sys.path[0]+'/../qiskit/providers/aer/')
sys.path.insert(1, sys.path[0]+'/../')

import numpy as np
from qiskit.quantum_info.operators import Operator
from pulse_new.models.signals import VectorSignal, Constant,ConstantSignal,  Signal
from pulse_new.models.operator_models import OperatorModel

X = Operator.from_label('X')
Y = Operator.from_label('Y')
Z = Operator.from_label('Z')

In [46]:
r = 1.
w = 1.
#signals = [Constant(1.), ConstantSignal(1., w)]
signals = VectorSignal(lambda t: np.array([1., 1.]), np.array([0., w]), np.array([1., 0.]))
operators = [-1j * 2 * np.pi * w * Z/2, -1j * 2 * np.pi * r * X/2]

In [47]:
model = OperatorModel(operators=operators, signals=signals)

In [42]:
model.evaluate(0.3)

array([[0.-3.14159265j, 0.+0.97080552j],
       [0.+0.97080552j, 0.+3.14159265j]])

In [43]:
model.frame_operator = model.drift

In [45]:
from time import time
start = time()
model.evaluate(1.3)
print(time() - start)

0.00020694732666015625


In [27]:
np.array([[1,2,3]]).transpose()

array([[1],
       [2],
       [3]])

In [48]:
model.drift

array([[0.-3.14159265j, 0.+0.j        ],
       [0.+0.j        , 0.+3.14159265j]])