In [1]:
import sys
sys.path.insert(1, sys.path[0]+'/../qiskit/providers/aer/')
sys.path.insert(1, sys.path[0]+'/../')

import numpy as np
from qiskit.quantum_info.operators import Operator
from pulse_new.models.signals import VectorSignal, Constant,ConstantSignal,  Signal
from pulse_new.models.operator_models import OperatorModel

X = Operator.from_label('X')
Y = Operator.from_label('Y')
Z = Operator.from_label('Z')

In [9]:
r = 1.
w = 1.
signals = [Constant(1.), ConstantSignal(1., w)]
operators = [2 * np.pi * w * Z/2, 2 * np.pi * r * X/2]

In [10]:
model = OperatorModel(operators=operators, signals=signals)

In [12]:
model.evaluate(0.3)

array([[ 3.14159265+0.j, -0.97080552+0.j],
       [-0.97080552+0.j, -3.14159265+0.j]])

In [5]:
isinstance([1,23,3], list)

True

In [14]:
np.outer(np.array([1,2,3]), np.array([1,2j,3]))

array([[1.+0.j, 0.+2.j, 3.+0.j],
       [2.+0.j, 0.+4.j, 6.+0.j],
       [3.+0.j, 0.+6.j, 9.+0.j]])

In [16]:
np.array([[1,2,3]]).transpose()

array([[1],
       [2],
       [3]])